// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One normalized event: an envelope (who, when, what order, which conversation)
 * wrapping a [`payload`](Self::payload) (what happened).
 */
export type AgentEvent = { id: string, sessionId: string, harness: Harness, 
/**
 * Position in the session's event log, and the cursor for reconnecting a UI
 * to a running session. One counter per session, shared by mapped stdout
 * lines and events the app synthesizes itself, seeded from the persisted log
 * on resume. Never sort by `ts` — most Claude Code events omit it.
 */
seq: number, ts: string, turnId: string | null, 
/**
 * `None` = main conversation, `Some` = the subagent that produced this.
 */
subagent: Subagent | null, payload: AgentEventPayload, 
/**
 * `None` on the emitted path — raw lines are archived separately — but
 * always populated for [`AgentEventPayload::Unknown`], which is useless
 * without it.
 */
raw: JsonValue | null, };

/**
 * What happened.
 *
 * Permission request/resolve is deliberately absent: no captured fixture shows
 * their shape, so the variants would be a guess. Add once captured.
 */
export type AgentEventPayload = { "type": "turn_started" } & SessionInfo | { "type": "turn_completed", status: TurnStatus, stopReason: string | null, finalText: string | null, usage: Usage | null, durationMs: number | null, 
/**
 * The working tree as this turn finished, as a git tree id — the
 * "after" side the changes panel diffs against once the turn is over.
 *
 * Without it the panel's head is always *now*, so an idle session
 * keeps absorbing whatever later touches the same checkout — another
 * session's turns, the user's editor — and describes them as this
 * turn's work. Freezing the head here bounds the diff to the turn.
 *
 * Filled by the session layer, not the mapper: only it knows the
 * session's cwd. `None` for a non-repo and for turns logged before
 * the field existed, which the panel reads as "diff against now".
 */
head: string | null, } | { "type": "settings_changed" } & Settings | { "type": "user_message", text: string, images: Array<ImageRef>, 
/**
 * The working tree as it stood when this prompt was sent, as a git
 * tree id — the "before" side the changes panel diffs against.
 *
 * Taken here rather than derived from the turn's own tool calls
 * because those miss everything `Bash` does, and because an `Edit`
 * carries only the fragment it replaced. A snapshot compares content,
 * so several edits to one file — and any commit made mid-turn —
 * collapse into the one net diff.
 *
 * `None` for a directory that isn't a repo, and for every prompt
 * logged before this field existed. Both mean the same thing to the
 * panel: nothing to show.
 */
baseline: string | null, 
/**
 * Typed while a turn was already running, so the CLI folds it into that
 * turn rather than starting a new one.
 *
 * Two transcript rules read this and both invert on it: a queued prompt
 * does not abandon the tool calls open before it — it is not proof the
 * turn stopped — and it does not cut a new turn, because the CLI answers
 * it inside the running one and emits a single `result` for both.
 */
queued: boolean, 
/**
 * The Dray session that relayed this prompt, when one did.
 *
 * `None` — the ordinary case — means the user typed it. Carried as a
 * field rather than named in `text` because the transcript draws the
 * sender, and anything drawn from prose the model can write itself is
 * a thing the model can forge.
 */
from: MessageSender | null, } | { "type": "assistant_text", 
/**
 * `Some` only when this content was also streamed, naming the preview
 * it supersedes. `None` — the common case, covering Claude Code
 * subagents and all of Codex — means nothing was streamed and the
 * event simply appends in `seq` order.
 */
block: BlockRef | null, text: string, } | { "type": "reasoning", block: BlockRef | null, text: string, encrypted: boolean, } | { "type": "delta" } & DeltaEvent | { "type": "tool_call_started", callId: string, 
/**
 * The harness's own tool name, verbatim (`"Bash"`, `"apply_patch"`).
 */
name: string, toolType: ToolType, 
/**
 * Always an object. JSON-encoded argument strings are parsed here;
 * unparseable input becomes `{"_unparsed": "…"}` rather than dropped.
 */
input: JsonValue, 
/**
 * Input that isn't JSON at all — Codex's `custom_tool_call.input` is raw
 * JS source.
 */
rawInput: string | null, title: string | null, } | { "type": "tool_call_completed", callId: string, result: ToolResult, } | { "type": "file_edits", callId: string | null, edits: Array<FileEdit>, } | { "type": "subagent_started", agentId: string, label: string, description: string | null, prompt: string | null, } | { "type": "subagent_progress", agentId: string, 
/**
 * What the subagent is doing right now — Claude Code rewrites this per
 * progress event, so it drives a live status line without expanding
 * the subagent's own events.
 */
description: string | null, lastTool: string | null, usage: Usage | null, } | { "type": "subagent_completed", agentId: string, status: string, summary: string | null, usage: Usage | null, } | { "type": "background_tasks_changed", tasks: Array<BackgroundTask>, } | { "type": "usage_update" } & Usage | { "type": "rate_limited", 
/**
 * `allowed` is the steady state and never reaches here.
 */
status: string | null, 
/**
 * When the window rolls over, RFC3339 — converted from the unix
 * seconds the wire sends.
 */
resetsAt: string | null, 
/**
 * Which window. `five_hour` observed, and at least one longer window
 * is believed to exist; not branched on anywhere.
 */
limitType: string | null, 
/**
 * Whether overage is available, which is what separates "blocked
 * until it resets" from "still working, now billed as usage".
 */
overageStatus: string | null, 
/**
 * Requests are already being billed as usage rather than covered.
 */
usingOverage: boolean, 
/**
 * Why overage isn't available — `org_level_disabled` observed.
 */
overageDisabledReason: string | null, } | { "type": "permission_requested", 
/**
 * Correlates the reply. Also what
 * [`PermissionDecided`](Self::PermissionDecided) joins on, which is how
 * a reloaded transcript knows an answered request from a live one.
 */
requestId: string, 
/**
 * The call being held. The matching
 * [`ToolCallStarted`](Self::ToolCallStarted) is already in the
 * transcript, so a renderer can show the request against the call
 * rather than repeating its arguments.
 */
toolUseId: string, toolName: string, 
/**
 * Preferred over `tool_name` for display when present.
 */
displayName: string | null, title: string | null, description: string | null, input: JsonValue, 
/**
 * The path that caused a working-directory escalation.
 */
blockedPath: string | null, 
/**
 * Why this escalated, in prose. May carry ANSI escapes — sanitize
 * before rendering.
 */
decisionReason: string | null, 
/**
 * Machine-readable counterpart to `decision_reason`: `safetyCheck`,
 * `rule`, `mode`, `workingDir` and others. Lets a consumer treat a
 * safety escalation differently without parsing prose.
 */
decisionReasonType: string | null, 
/**
 * Set when a subagent made the call rather than the main thread.
 *
 * Not a correlation key — it is the harness's own handle and matches no
 * other id — so it answers exactly one question: whether the call being
 * consented to is visible to the reader. A main-thread request renders
 * directly under its own `ToolCallStarted` row; a subagent's renders
 * with that row filed away in a panel, so the card has to carry the
 * arguments itself or it asks about something invisible.
 */
agentId: string | null, options: Array<PermissionOption>, } | { "type": "questions_asked", requestId: string, 
/**
 * The `AskUserQuestion` call being held. Its own row is already in the
 * transcript and will show the answers once it completes.
 */
toolUseId: string, 
/**
 * One to four, per the tool's own schema.
 */
questions: Array<Question>, } | { "type": "permission_decided", requestId: string, toolUseId: string, behavior: PermissionBehavior, 
/**
 * The chosen option's label, so the transcript reads back as what the
 * user actually picked rather than a bare allow/deny.
 */
label: string, 
/**
 * True when the app answered on its own — an unsupported request
 * subtype, or a shutdown clearing what it could not ask about.
 */
automatic: boolean, } | { "type": "permission_denied", toolName: string, toolUseId: string, message: string, } | { "type": "hook", name: string, event: string, phase: HookPhase, exitCode: number | null, outcome: string | null, } | { "type": "model_request_started" } | { "type": "context_compaction_started" } | { "type": "context_compacted", 
/**
 * `manual` or `auto`.
 */
trigger: string | null, preTokens: number | null, postTokens: number | null, durationMs: number | null, } | { "type": "error", source: ErrorSource, message: string, fatal: boolean, } | { "type": "unknown", harnessType: string, } | { "type": "unrecognized" };

/**
 * Permission stance a session *runs under*, in roughly increasing order of
 * autonomy. Every variant is settable, so this is what the app stores and
 * sends — see [`PermissionMode`] for the wider set the CLI reports.
 */
export type ApprovalPolicy = "plan" | "manual" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

/**
 * One thing the user attached, as the composer needs to draw it.
 */
export type Attachment = { 
/**
 * Where it was picked from. This is the identity the composer dedupes on
 * and the path the backend re-reads at send time — nothing but paths
 * crosses back down, so a 4MB preview is never uploaded twice.
 */
path: string, name: string, 
/**
 * Only meaningful for an image; `None` says nothing about the file beyond
 * "not something we send as pixels".
 */
mimeType: string | null, size: number, 
/**
 * Whether this will travel as an image block. Decided by extension *and*
 * size together, so the composer's thumbnail and the wire agree.
 */
isImage: boolean, 
/**
 * A `data:` URL for the composer's thumbnail, `None` for a file. Sent up
 * once and held in frontend memory only — the persisted event points at a
 * copy on disk instead, so the session log never carries image bytes.
 */
preview: string | null, };

/**
 * One outstanding background task. The harness's wire shape is snake_case, so
 * the parser keeps its own struct and the mapper converts — sharing this one
 * would break on `task_id` vs `taskId`.
 */
export type BackgroundTask = { taskId: string, 
/**
 * Free-form kind string — `local_agent` observed, set undocumented.
 */
taskType: string, description: string, };

/**
 * Joins streamed content to its committed counterpart. A message is often
 * `[text, tool_use, …]` and each block arrives as its own event; Claude Code's
 * committed events carry no index, so the mapper derives one by counting blocks
 * per `message_id` in arrival order.
 */
export type BlockRef = { messageId: string, index: number, };

/**
 * A tool call's identity rides here rather than on [`BlockRef`], which stays a
 * cheap map key. It arrives before any arguments have streamed, so the UI can
 * label the call while [`DeltaEvent::InputDelta`] fragments are still landing.
 */
export type BlockType = { "type": "text" } | { "type": "thinking" } | { "type": "tool_use", id: string, name: string, };

/**
 * What the composer's branch picker needs to render and guard itself.
 */
export type BranchList = { 
/**
 * `None` on a detached HEAD, and for a directory that isn't a repo.
 */
current: string | null, branches: Array<string>, 
/**
 * What a `-w` worktree forks from, resolved the way the CLI resolves it.
 * Shown in place of the branch picker in worktree mode, where the picked
 * branch has no effect. `None` when the repo has no remote.
 */
defaultBase: string | null, 
/**
 * Uncommitted changes, counted for the switch dialog's "you have N
 * changes". Zero switches without asking.
 */
dirty: number, };

/**
 * Everything that changed between two snapshots.
 */
export type ChangeSet = { base: string, 
/**
 * The snapshot taken to answer *this* request. Handed back so a follow-up
 * read of one file's contents resolves against the same tree the list was
 * built from — the working tree moves under a running agent, and a file
 * list and a diff taken a second apart would otherwise disagree.
 */
head: string, files: Array<ChangedFile>, added: number, removed: number, };

export type ChangeStatus = "added" | "modified" | "deleted" | "renamed";

/**
 * How one path differs between two snapshots. `added`/`removed` are git's own
 * numstat figures, so the row and the diff it opens cannot disagree.
 */
export type ChangedFile = { 
/**
 * The path as of the *new* side — where a renamed file ended up.
 */
path: string, 
/**
 * Only a rename sets this: the name the file had in the baseline, which is
 * also the name its old side has to be read under.
 */
oldPath: string | null, status: ChangeStatus, added: number, removed: number, 
/**
 * Git reports `-` for both counts here rather than a number. Listed like
 * any other change, but with no diff to open.
 */
binary: boolean, };

/**
 * Where a check ended up, flattened from the two different shapes GitHub
 * reports one in. Callers branch on this and never on the wire's own strings.
 */
export type CheckState = "success" | "failure" | "pending" | "skipped" | "cancelled" | "neutral";

/**
 * What kind of entry a timeline row is. A review carries a verdict where a
 * plain comment carries none, and that verdict is most of what the row says.
 */
export type CommentKind = "comment" | "approved" | "changes_requested" | "reviewed";

/**
 * One commit, as the history list draws it.
 */
export type Commit = { sha: string, 
/**
 * First parent — the side this commit's own diff is taken against. `None`
 * on the root commit, where the caller substitutes git's empty tree. A
 * merge keeps only its first parent, so it reads as what the merge brought
 * onto this branch rather than as everything both sides ever did.
 */
parent: string | null, subject: string, body: string, author: string, 
/**
 * What the history list draws a face from. Git has no account behind a
 * commit — only whatever the author configured — so this is the only
 * identity here, and the frontend resolves it to a picture or to a letter.
 */
authorEmail: string, 
/**
 * RFC 3339, matching every other timestamp that reaches the frontend.
 */
authoredAt: string, };

export type ContextWindow = { usedTokens: number, maxTokens: number, };

/**
 * Incremental content for a block.
 *
 * **Deltas are a preview, never the source of truth**: the committed event for
 * the same [`BlockRef`] supersedes whatever they accumulated. Absent deltas are
 * the common case — Codex emits none, Claude Code none for subagent output — so
 * consumers must render correctly without them.
 * Tagged on `delta`, not `type`: [`AgentEventPayload::Delta`] is a newtype
 * variant, so these fields flatten into the payload object alongside its own
 * `type` tag. Two tags of the same name serialize but never deserialize.
 */
export type DeltaEvent = { "delta": "block_start", block: BlockRef, blockType: BlockType, } | { "delta": "text_delta", block: BlockRef, text: string, } | { "delta": "input_delta", block: BlockRef, partialJson: string, } | { "delta": "block_stop", block: BlockRef, };

export type Effort = "low" | "medium" | "high" | "xhigh" | "max";

export type ErrorSource = "harness" | "parser" | "process";

export type FileChange = "add" | "update" | "delete";

export type FileEdit = { path: string, change: FileChange, unifiedDiff: string | null, };

/**
 * One row in the picker. `path` is relative to the indexed directory, which is
 * also what gets typed into the prompt — the CLI resolves `@path` against the
 * same cwd the child was spawned in, so no rewriting is needed on either side.
 */
export type FileMatch = { path: string, 
/**
 * The last segment, split out so the row can weight the name over the
 * directory rather than making the reader find it inside the path.
 */
name: string, 
/**
 * Everything before `name`, without a trailing slash. Empty at the root.
 */
dir: string, };

/**
 * Both sides of one file's change, as the text a diff viewer compares.
 */
export type FileVersions = { 
/**
 * `None` for a file the baseline didn't have — the viewer draws an
 * addition rather than a diff against the empty string.
 */
oldText: string | null, 
/**
 * `None` for a file the turn deleted.
 */
newText: string | null, 
/**
 * Set when a side exists but is being withheld, so the panel can name the
 * reason instead of drawing an empty diff and looking broken.
 */
unreadable: Unreadable | null, };

export type Harness = "claude_code" | "codex";

export type HookPhase = "started" | "finished";

export type ImageRef = { path: string | null, url: string | null, mimeType: string | null, };

/**
 * Shared with the harness parsers rather than duplicated — the wire shape
 * matches, so they deserialize straight into this.
 */
export type McpServer = { name: string, 
/**
 * Free-form: `connected`, `pending`, `needs-auth` observed, set undocumented.
 */
status: string, };

/**
 * How to land it. The three GitHub offers; the flag each maps to is `gh`'s.
 */
export type MergeMethod = "merge" | "squash" | "rebase";

/**
 * Who relayed a prompt into this session, for a `user_message` the user did
 * not type.
 *
 * Both fields are needed and neither substitutes for the other: the title is
 * what the reader recognizes — it is what the sidebar shows — and the id is
 * what the transcript navigates to when they click it.
 *
 * Persisted, unlike most of what the app synthesizes: the transcript is
 * replayed from the log, so attribution that lived only in memory would be
 * gone on the next open.
 */
export type MessageSender = { sessionId: string, title: string, };

export type Model = { 
/**
 * What `--model` receives.
 */
id: ModelId, label: string, 
/**
 * Empty means the model has no effort levels. The CLI tolerates `--effort`
 * on such a model and ignores it, so this drives the UI and keeps the
 * persisted value honest rather than preventing a crash.
 */
efforts: Array<Effort>, defaultEffort: Effort | null, };

/**
 * The `--model` alias, typed. `Unknown` exists so an index entry naming a
 * model this build no longer lists still deserializes — losing one session's
 * model beats failing the whole index read and emptying the sidebar. It maps
 * to no alias, so [`find_model`] rejects it and it can't reach a spawn.
 */
export type ModelId = "opus" | "sonnet" | "fable" | "haiku" | "unknown";

/**
 * What one model has consumed **for the session so far** — cumulative and
 * monotonic across turns, not a per-turn figure.
 *
 * That is the whole reason it is carried and persisted. [`Usage`]'s own counts
 * are the harness's per-turn sum over every main-thread message, which double
 * counts a context re-read once per tool call and so describes neither the turn
 * nor the context. Here a turn's real consumption is the difference between
 * consecutive readings.
 *
 * Every field is optional and the harness's own map is left untyped upstream:
 * this rides `turn_completed`, and a `result` line that fails to parse strands
 * the session on `in_progress`. A shape we don't recognize must cost this
 * struct a field, never the line.
 */
export type ModelUsage = { 
/**
 * The harness's own key — a dated id (`claude-haiku-4-5-20251001`), not the
 * alias a session was started with.
 */
model: string, inputTokens: number | null, outputTokens: number | null, cachedInputTokens: number | null, cacheWriteTokens: number | null, webSearchRequests: number | null, costUsd: number | null, 
/**
 * This model's context window. Also what the composer's gauge measures
 * against — see `context_window` in the Claude Code mapper.
 */
contextWindow: number | null, maxOutputTokens: number | null, };

export type PermissionBehavior = "allow" | "deny";

/**
 * What the CLI *reports* in `system/init`, which is a wider set than it
 * accepts: `default` names the harness's own prompting stance, and
 * `--permission-mode` rejects that name while offering `manual` for the same
 * thing. Kept separate from [`ApprovalPolicy`] rather than remapped, so a
 * round trip can't quietly turn one into the other.
 */
export type PermissionMode = "default" | "plan" | "manual" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

/**
 * One answer the user can give to a [permission
 * request](AgentEventPayload::PermissionRequested).
 *
 * Deliberately carries no wire payload. The standing rule an option would
 * apply is the harness's to compose and the harness's to send, so the app
 * replies with [`id`](Self::id) alone and the harness resolves it — which keeps
 * a rule that grants more than it appears to from ever being assembled on the
 * UI side.
 */
export type PermissionOption = { 
/**
 * Unique within its request, and the whole of what the app sends back.
 */
id: string, label: string, kind: PermissionOptionKind, 
/**
 * Whether picking this lets the call run. Both `Deny` kinds carry
 * [`Deny`](PermissionBehavior::Deny); everything else allows.
 */
behavior: PermissionBehavior, };

/**
 * What an option *does*, for a renderer that wants to group or order them.
 * The set is closed on purpose: an unmappable suggestion is dropped rather
 * than shown as a button whose effect can't be described.
 */
export type PermissionOptionKind = "once" | "always_rule" | "always_directory" | "switch_mode" | "deny";

export type PrCheck = { name: string, state: CheckState, 
/**
 * Where the log lives. `None` for a check that reports no link.
 */
url: string | null, 
/**
 * The Actions workflow this run belongs to, when it is one — several
 * workflows can contribute checks of the same name.
 */
workflow: string | null, 
/**
 * The mark of whoever reports this check — Vercel's logo on a Vercel
 * check. It is what makes a list of check names scannable without reading
 * them, and it cannot be built from the login: see [`QUERY`].
 */
avatar: string | null, };

/**
 * What CI on the tip commit has to say, cut to the two things a row can show.
 *
 * Passing is folded in with "no checks at all" on purpose: a row that says
 * nothing is a row with nothing to do, and marking every green branch green a
 * second time makes the mark that *does* need reading harder to find. So this
 * is a three-way, not the rollup's five-way — `SUCCESS` and an absent rollup
 * both reach the reader as [`PrChecksState::Clear`].
 */
export type PrChecksState = "RUNNING" | "FAILING" | "CLEAR";

export type PrComment = { author: string, 
/**
 * The commenter's picture. `None` for an account that has none, which the
 * panel draws as their initial rather than as a gap.
 */
avatar: string | null, body: string, createdAt: string, url: string, kind: CommentKind, 
/**
 * The file an inline review comment hangs on — `path:line`, or the path
 * alone once GitHub has forgotten which line it pointed at. `None` for
 * everything on the conversation timeline, which hangs on nothing.
 */
path: string | null, 
/**
 * Whether the thread has been settled. False for every row that is not a
 * thread, since only a review thread can be resolved.
 */
resolved: boolean, 
/**
 * The rest of the thread, oldest first. Only an inline comment carries
 * any: a PR's own conversation is flat, so a reply is either part of a
 * review thread or it is a new comment.
 */
replies: Array<PrComment>, };

/**
 * One pull request, cut down to what a sidebar row can draw.
 *
 * Deliberately not a `PullRequest`: the row says "this branch has a PR, and
 * what became of it" and nothing else, so carrying checks, comments and review
 * threads for every session in the list would be payload nobody reads.
 */
export type PrMark = { number: number, 
/**
 * The branch it was opened from — what the caller matches a session by.
 */
headRefName: string, isDraft: boolean, state: PrMarkState, checksState: PrChecksState, 
/**
 * Enough of the panel's merge fields to answer "can this land now", which
 * the sidebar itself draws nothing from — the notice for a pull request
 * turning ready does, and this is the only read that runs for a session
 * nobody is looking at. The panel's query is gated on its own tab being
 * on screen, which is precisely when there is nothing to announce.
 *
 * `None` on the merged half, where they are not asked for. The frontend
 * reads that as *unknown* rather than as ready — see `mergeVerdict`.
 */
mergeable: string | null, mergeStateStatus: string | null, };

/**
 * Which of the two connections a mark came from.
 *
 * Not parsed off the wire: [`QUERY_MARKS`] asks each state in its own aliased
 * connection, so the connection *is* the answer and a `state` field would be a
 * second copy of it free to disagree. Only the two states the sidebar draws —
 * closed-without-merging is not asked for.
 */
export type PrMarkState = "OPEN" | "MERGED";

/**
 * Why there is nothing to show, when the reason is not "this branch has no PR".
 *
 * Typed rather than a string because the frontend acts differently on each:
 * a missing `gh` hides the tab outright — the app has no business claiming a
 * GitHub feature on a machine with no GitHub CLI — while a `gh` that is merely
 * logged out keeps the tab and says so, since someone who installed it clearly
 * works with GitHub and the fix is one command.
 */
export type PrUnavailable = { "kind": "no_cli" } | { "kind": "not_authenticated" } | { "kind": "no_remote" } | { "kind": "other", "detail": string };

/**
 * A directory the user attached, and the root a session runs in. Distinct from
 * [`crate::store::SessionIndexItem::project_path`], which records where a
 * session *did* run — a project can be detached without rewriting history.
 */
export type Project = { 
/**
 * Canonicalized at attach time, so this is the only spelling of the path
 * that ever reaches the index or the sidebar's grouping key.
 */
path: string, 
/**
 * Folder name as of attaching. Cached so a project whose directory was
 * since renamed or removed still has a label.
 */
name: string, 
/**
 * Doubles as the sort key and the "which project was last open" answer:
 * selecting a project *is* what makes it most recent, so a separate
 * `last_selected` pointer would be a second place to keep the same fact.
 */
lastSelected: string, };

export type PullRequest = { number: number, title: string, url: string, 
/**
 * `OPEN`, `CLOSED` or `MERGED`, carried through as GitHub's own word.
 */
state: string, isDraft: boolean, author: string, baseRefName: string, headRefName: string, 
/**
 * `MERGEABLE`, `CONFLICTING`, or `UNKNOWN` while GitHub is still working
 * the merge out — which it starts doing lazily, on being asked.
 */
mergeable: string, 
/**
 * The finer answer: `CLEAN`, `BLOCKED`, `BEHIND`, `DIRTY`, `UNSTABLE`,
 * `DRAFT`, `HAS_HOOKS`, `UNKNOWN`.
 */
mergeStateStatus: string, 
/**
 * `APPROVED`, `CHANGES_REQUESTED`, `REVIEW_REQUIRED`. `None` where the
 * repo requires no review, which `gh` reports as an empty string.
 */
reviewDecision: string | null, checks: Array<PrCheck>, 
/**
 * Comments, reviews and inline threads in one list, oldest first — the
 * order GitHub reads them in, and the only order in which a bot's reply to
 * a review makes sense. A thread is one entry carrying its own replies.
 */
comments: Array<PrComment>, 
/**
 * Lines added and removed across the whole PR, and how many files moved.
 * The same figures the changes panel shows for a turn, for the same
 * reason: a row naming a PR says nothing about how much of one it is.
 */
additions: number, deletions: number, changedFiles: number, updatedAt: string, };

/**
 * One question from a [`QuestionsAsked`](AgentEventPayload::QuestionsAsked).
 *
 * [`question`](Self::question) is both the prompt and the key its answer is
 * filed under, so the text has to survive the round trip unchanged — the
 * harness matches on it verbatim.
 */
export type Question = { question: string, 
/**
 * A short chip label for the question — "Indentation", "Auth method".
 */
header: string | null, 
/**
 * Whether several options may be picked, in which case the answer is one
 * comma-separated string rather than a list.
 */
multiSelect: boolean, 
/**
 * Two to four, per the tool's own schema. Never exhaustive: the harness
 * promises the user a free-text box alongside them, and instructs the model
 * not to offer an "Other" option because of it — so a renderer that shows
 * only these takes an answer away.
 */
options: Array<QuestionOption>, };

export type QuestionOption = { 
/**
 * What the user picks, and what travels back as the answer — the harness
 * has no option ids, so the label is the value.
 */
label: string, description: string | null, 
/**
 * Markdown the harness expects shown in a monospace box. Single-select
 * questions only.
 */
preview: string | null, };

/**
 * A prompt typed while a turn was running, held here until the turn reaches a
 * point where handing it to the CLI costs nothing.
 *
 * It is *not* persisted while it waits, and that is what makes cancelling it
 * clean: the log is append-only, so a queued message written on arrival could
 * only be retracted with a tombstone event. Held here instead, a cancel leaves
 * no trace at all. Nothing is lost by waiting — the flush persists it, and the
 * only window where it exists solely in memory is one the user is still
 * allowed to take it back from.
 */
export type QueuedMessage = { id: string, sessionId: string, 
/**
 * The raw prompt. Attachments are resolved at flush rather than now, so
 * what the composer gets back on a cancel is what the user typed.
 */
text: string, attachmentPaths: Array<string>, 
/**
 * Held with the prompt rather than looked up at flush: a relayed message
 * can wait out a long turn, and the sending session may be renamed or
 * deleted before the boundary that delivers it.
 */
from: MessageSender | null, };

export type RateLimit = { usedPercent: number | null, windowMinutes: number | null, 
/**
 * RFC3339, normalized from whatever the harness reports.
 */
resetsAt: string | null, planType: string | null, };

/**
 * What a send did. The two fields are mutually exclusive in practice — a
 * session being created cannot already be running a turn — but they answer
 * different questions and the frontend acts on each separately.
 */
export type SendOutcome = { 
/**
 * `Some` only when this send created the session.
 */
snapshot: SessionSnapshot | null, 
/**
 * `Some` when a turn was already running, so the prompt is held rather
 * than sent. The frontend draws it as pending and can still take it back.
 */
queued: QueuedMessage | null, };

export type SessionIndexItem = { sessionId: string, harness: Harness, 
/**
 * Where the agent actually runs. Equals `project_path` for a normal
 * session; points inside `.claude/worktrees/<name>` for a worktree one.
 */
cwd: string, 
/**
 * Repo root — the grouping key, so worktree sessions still list under
 * their project rather than each becoming a project of their own.
 */
projectPath: string, branch: string | null, 
/**
 * `Some` marks this a worktree session; Claude Code names the branch
 * `worktree-<name>`.
 */
worktreeName: string | null, 
/**
 * This session ran in a worktree and that tree has since been deleted, so
 * `cwd` is the project root it was moved back to. The distinction is what
 * keeps `branch` above authoritative: the shared checkout's HEAD describes
 * whatever else is going on in it, not this session's work.
 */
worktreeRemoved: boolean, title: string, 
/**
 * Remembered per session so switching between sessions restores the model
 * the user last picked instead of resetting to a default.
 */
model: ModelId, 
/**
 * `None` for models that take no effort flag.
 */
effort: Effort | null, 
/**
 * Defaulted so entries written before this field read as the CLI's own
 * default rather than failing the whole index.
 */
permissionMode: ApprovalPolicy, 
/**
 * Defaulted so index entries written before this field parse as `Idle`.
 */
status: SessionStatus, 
/**
 * An instruction, not a record of lineage: the session this one was forked
 * from, set until the CLI has actually forked. The fork is lazy — copying
 * this app's own log and index entry is instant, while the CLI's half only
 * happens on a spawn — so the first send resumes the parent with
 * `--fork-session` and clears this. Every send after is an ordinary resume.
 *
 * Distinct from `parent_session_id` below, which is lineage and permanent:
 * this one is cleared the moment the CLI carries the fork out.
 */
forkFrom: string | null, 
/**
 * The session whose agent created this one, for a session created over the
 * orchestration socket rather than by a person in the composer. `Some` is
 * also what the depth guard reads: a session that was itself spawned may
 * not spawn more.
 */
parentSessionId: string | null, created: string, modified: string, archived: boolean, pinned: boolean, };

/**
 * Session-level facts, known at startup.
 */
export type SessionInfo = { cwd: string | null, model: string | null, harnessVersion: string | null, tools: Array<string>, mcpServers: Array<McpServer>, subagentTypes: Array<string>, settings: Settings | null, };

/**
 * What crosses the IPC boundary for one session: its index entry plus the
 * replayed event log. Distinct from [`crate::session::Session`], which owns a
 * child process and cannot be serialized.
 */
export type SessionSnapshot = { events: Array<AgentEvent>, sessionId: string, harness: Harness, 
/**
 * Where the agent actually runs. Equals `project_path` for a normal
 * session; points inside `.claude/worktrees/<name>` for a worktree one.
 */
cwd: string, 
/**
 * Repo root — the grouping key, so worktree sessions still list under
 * their project rather than each becoming a project of their own.
 */
projectPath: string, branch: string | null, 
/**
 * `Some` marks this a worktree session; Claude Code names the branch
 * `worktree-<name>`.
 */
worktreeName: string | null, 
/**
 * This session ran in a worktree and that tree has since been deleted, so
 * `cwd` is the project root it was moved back to. The distinction is what
 * keeps `branch` above authoritative: the shared checkout's HEAD describes
 * whatever else is going on in it, not this session's work.
 */
worktreeRemoved: boolean, title: string, 
/**
 * Remembered per session so switching between sessions restores the model
 * the user last picked instead of resetting to a default.
 */
model: ModelId, 
/**
 * `None` for models that take no effort flag.
 */
effort: Effort | null, 
/**
 * Defaulted so entries written before this field read as the CLI's own
 * default rather than failing the whole index.
 */
permissionMode: ApprovalPolicy, 
/**
 * Defaulted so index entries written before this field parse as `Idle`.
 */
status: SessionStatus, 
/**
 * An instruction, not a record of lineage: the session this one was forked
 * from, set until the CLI has actually forked. The fork is lazy — copying
 * this app's own log and index entry is instant, while the CLI's half only
 * happens on a spawn — so the first send resumes the parent with
 * `--fork-session` and clears this. Every send after is an ordinary resume.
 *
 * Distinct from `parent_session_id` below, which is lineage and permanent:
 * this one is cleared the moment the CLI carries the fork out.
 */
forkFrom: string | null, 
/**
 * The session whose agent created this one, for a session created over the
 * orchestration socket rather than by a person in the composer. `Some` is
 * also what the depth guard reads: a session that was itself spawned may
 * not spawn more.
 */
parentSessionId: string | null, created: string, modified: string, archived: boolean, pinned: boolean, };

/**
 * Driven by [`StatusTracker`](crate::session::StatusTracker). `Completed`
 * means finished *and unread* — the transition back to `Idle` is the user
 * looking at the session, not anything the agent does.
 */
export type SessionStatus = "idle" | "in_progress" | "completed";

/**
 * Emitted as `session_status` when a session's status changes, so the sidebar
 * and composer update without a refetch. Like `SessionTitleEvent`, this is not
 * an `AgentEvent`: it's derived state, and must never reach the `.jsonl` log.
 */
export type SessionStatusEvent = { sessionId: string, status: SessionStatus, 
/**
 * The entry's `modified` as the status write left it — completion bumps it,
 * and the sidebar orders by it, so a session finishing has to move to the
 * top without a refetch. `None` only when the id is no longer indexed.
 */
modified: string | null, };

/**
 * Emitted as `session_title` once a generated title lands, so the sidebar row
 * updates without a refetch. Not an `AgentEvent`: nothing here came from the
 * agent, and it must never reach the session's `.jsonl` log.
 */
export type SessionTitleEvent = { sessionId: string, title: string, };

/**
 * Settings that can change mid-session, so they arrive as events rather than
 * living only on [`SessionInfo`].
 */
export type Settings = { model: string | null, 
/**
 * How much the agent may do without asking. Modeled on Claude Code's
 * `permissionMode`, which is a closed set; Codex's `approval_policy` maps
 * onto these, gaining variants if it turns out to need them.
 */
approvalPolicy: PermissionMode | null, sandbox: string | null, writableRoots: Array<string>, networkAccess: boolean | null, fastMode: string | null, };

/**
 * One command the user may type. `name` carries no leading slash — the picker
 * adds it — and may be namespaced by its plugin (`railway:deploy`).
 */
export type SlashCommand = { name: string, description: string, 
/**
 * What the command does with the rest of the line — `<model>`, `[name]`.
 * Empty for most; the CLI sends `""` rather than omitting it.
 */
argumentHint: string, 
/**
 * Other names that reach the same command. Absent on most.
 */
aliases: Array<string>, };

/**
 * A running subagent, whose events interleave with the main conversation's on
 * one stdout stream.
 *
 * Claude Code identifies these by `parent_tool_use_id` — the id of the tool
 * call that spawned it, so this equals the `call_id` of the corresponding
 * [`AgentEventPayload::ToolCallStarted`] and is what nests a subagent's work
 * under it. Codex uses `agent_path`.
 */
export type Subagent = { id: string, 
/**
 * Drives the collapsed subagent card's title.
 */
label: string | null, };

/**
 * Where the current branch stands against its upstream — everything the push
 * button needs to name itself.
 */
export type SyncStatus = { 
/**
 * `None` on a detached HEAD and for a directory that isn't a repo, which
 * is how the row hides itself rather than offering a push it can't do.
 */
branch: string | null, 
/**
 * `None` for a branch that has never been pushed — the "publish" case.
 */
upstream: string | null, 
/**
 * Commits the upstream doesn't have. Zero when there is no upstream: the
 * button reads "Publish branch" there, and a count would be answering a
 * question nobody asked yet.
 */
ahead: number, };

export type ToolResult = { 
/**
 * Result content flattened to text; harnesses vary between a bare string
 * and an array of blocks.
 */
text: string, 
/**
 * Harnesses routinely omit the error flag on success, so this defaults to
 * `false` rather than being treated as unknown.
 */
isError: boolean, 
/**
 * The full result payload when the harness supplies a structured one.
 */
structured: JsonValue | null, exitCode: number | null, durationMs: number | null, 
/**
 * Pictures the tool handed back — a `Read` of a screenshot, an MCP tool
 * that answers in images. Archived under `~/.dray/attachments` before the
 * event is written, so this carries a path and never the bytes: the CLI
 * sends the same image twice on one line and a session of screenshots was
 * 12MB of base64 in a 14MB log.
 */
images: Array<ImageRef>, };

/**
 * A rendering hint — which icon and component to use. Nothing depends on this
 * for correctness, and [`ToolType::Other`] must always render acceptably.
 */
export type ToolType = "shell" | "file_read" | "file_edit" | "search" | "web" | "mcp" | "subagent_spawn" | "other";

/**
 * How a turn ended. Claude Code reports this as `is_error` on its result
 * event; Codex live emits `turn.completed` (a failed turn is uncaptured so
 * far). A user-abort outcome likely deserves its own variant once one has been
 * captured.
 */
export type TurnStatus = "success" | "error";

export type Unreadable = "binary" | "too_large";

export type UpdateChannel = "stable" | "beta";

/**
 * What the sidebar row draws. There is no idle variant: nothing is emitted
 * until an update exists, so the frontend's own `null` is the resting state
 * and a failed check leaves the UI exactly as it was.
 */
export type UpdateStatus = { "state": "downloading", version: string, 
/**
 * `None` until the server sends a content length, which not every
 * CDN does — the row shows an indeterminate state rather than 0%.
 */
percent: number | null, } | { "state": "ready", version: string, notes: string | null, };

export type Usage = { inputTokens: number | null, outputTokens: number | null, cachedInputTokens: number | null, cacheWriteTokens: number | null, 
/**
 * Broken out only by harnesses that report it separately; others fold
 * thinking tokens into `output_tokens`.
 */
reasoningTokens: number | null, totalTokens: number | null, costUsd: number | null, contextWindow: ContextWindow | null, rateLimit: RateLimit | null, model: string | null, 
/**
 * Session-cumulative consumption, split by model. Empty on every harness
 * and every event that doesn't report one. See [`ModelUsage`].
 */
perModel: Array<ModelUsage>, };

/**
 * What the composer's action row needs to decide which buttons it has, in one
 * read.
 *
 * A superset of [`SyncStatus`] rather than three calls stitched together in
 * the frontend: every field here answers the same question — "what is there
 * left to do with this work" — and reading them separately would let the row
 * draw a Commit button from one snapshot beside a Push count from another.
 */
export type WorkStatus = { 
/**
 * Uncommitted paths. A count and not a list — the row only asks whether
 * there is anything, and the changes view is where the files are read.
 */
dirty: number, 
/**
 * `None` on a detached HEAD and outside a repo, which is how the row hides
 * itself entirely.
 */
branch: string | null, 
/**
 * `None` for a branch never pushed — the "publish" case.
 */
upstream: string | null, ahead: number, 
/**
 * The branch this work would land on, short of its remote (`main`, not
 * `origin/main`). Stripped here rather than in the row, so "am I on the
 * default branch" is one comparison and not a parsing rule that can drift.
 * `None` where there is no remote to ask.
 */
defaultBranch: string | null, 
/**
 * Commits this branch holds that the default branch doesn't — what a pull
 * request would actually contain.
 *
 * A different question from [`ahead`], which counts against the *upstream*:
 * a branch pushed in full is `ahead: 0` and still the one case where a pull
 * request is most wanted. Reading `ahead` for this hides the button exactly
 * when it is needed.
 *
 * `None` is "couldn't tell", not zero — `origin/HEAD` can be a symref onto
 * a ref that was never fetched, and `symbolic-ref` resolves it without
 * checking. The row treats unknown as "there may be something", since
 * over-offering costs a wasted click and under-offering hides the action.
 */
aheadOfBase: number | null, };

/**
 * What removing this worktree would cost, read once so the dialog and the
 * removal agree about what is in the way.
 */
export type WorktreeDisposition = { 
/**
 * `false` once the directory is gone — removed by hand, or by a `claude`
 * run that did have an exit prompt. The caller skips the dialog and goes
 * straight to relocating the session, so a half-dead tree tidies itself
 * up rather than asking a question about a directory nobody can see.
 */
exists: boolean, 
/**
 * `git status --porcelain` lines: modified, staged, and untracked alike.
 */
changedFiles: number, 
/**
 * Commits **only this branch holds** — reachable from its HEAD and from
 * no other branch, remote or tag. That is the question the reader is
 * actually asking, since a commit some other ref also holds survives the
 * branch being deleted.
 *
 * Counting against remotes alone was the first version and was wrong in
 * the plainest case: a repo with no remote at all reported every commit
 * in its history as at risk, so a spotless worktree warned about the
 * initial commit.
 *
 * A squash-merged PR still counts, since its commits are genuinely on no
 * other ref whatever landed on `main`. The CLI's own exit prompt has the
 * same blind spot; it over-warns, which is the safe direction.
 */
unpushedCommits: number, 
/**
 * The reason string on git's own lock, when one is held by a **live**
 * process. `None` covers both the unlocked tree and the far commoner
 * case of a lock left behind by a session that has since exited.
 */
lockedBy: string | null, };
